### ISSUE TITLE
不知能否在dynablocks中增加支持1.8‘’TFT支持

### ISSUE THREAD

**Issue by bingoHome** [wwj718/microblocks-cn-group#1]
发现自带的dynablocks不支持esp32下的1.8‘’TFT（st7735），不知能否增加，又或者本身是支持的，我接错了引脚。

**Comment by wwj718** [comment]
应该支持的，是否运行这个积木？

<img width="696" alt="image" src="https://user-images.githubusercontent.com/3153878/155076053-696fcc63-4785-4977-a95e-c3223ca5d716.png">

**Comment by bingoHome** [comment]
我试了一下，没反应。是不是引脚接线有要求，我的接线如下：
TFT_CS         14
TFT_RST        2
TFT_DC         4
TFT_BL        15
TFT_SDA     23  
TFT_SCL      18 
![12](https://user-images.githubusercontent.com/11031916/155096021-95288a8d-3160-473a-b18f-2487fa32ddfb.png)

另外我看了一下显示的屏幕尺寸不对。
![2022-02-22_164231](https://user-images.githubusercontent.com/11031916/155095313-44619136-53a5-4d2b-be31-36dedac43aba.png)

**Comment by wwj718** [comment]
我手头暂无这个板子，或许可以从官方源码里一探究竟 https://bitbucket.org/john_maloney/smallvm/src/master/

**Comment by wwj718** [comment]
在issue里向作者提问可能比较简单 https://bitbucket.org/john_maloney/smallvm/issues

**Comment by bingoHome** [comment]
谢谢指点，在官方源码tftPrims中增加Esp32主板的有关声明，重新编译上传固件后搞定。
![2022-02-22_203629](https://user-images.githubusercontent.com/11031916/155134287-2c259b60-fb04-46d3-88e4-b8737b90b056.png)
![20220222204128](https://user-images.githubusercontent.com/11031916/155134603-57ad3ae8-7ef9-44a2-bbd2-a3aecf5ba84d.jpg)

**Comment by wwj718** [comment]
或许可以给官方提个PR
