### ISSUE TITLE
enable TFT的bug

### ISSUE THREAD

**Issue by bingoHome** [wwj718/microblocks-cn-group#2]
![2022-02-26_161216](https://user-images.githubusercontent.com/11031916/155835802-04527a0c-db41-425a-93f0-9149239580fe.png)
![2022-02-26_161254](https://user-images.githubusercontent.com/11031916/155835806-6048d802-2277-4dbc-a936-2b6bf0fb96aa.png)

**Comment by wwj718** [comment]
谢谢！

**Comment by wwj718** [comment]
已修复

**Comment by bingoHome** [comment]
不好意思，请问离线版的如何修复。

**Comment by wwj718** [comment]
我没处理过离线版呢
